import { theme as globalTheme } from '@styles/Theme';

export const animalRaceBetsTheme = {
    ...globalTheme,
  colors: {
    ...globalTheme.colors,
    primary: '#4F8A8B',
    secondary: '#FBD46D',
    background: '#F6F6F6',
    surface: '#FFFFFF',
    text: '#222831',
    accent: '#FF6F61',
    success: '#43AA8B',
    warning: '#F9A826',
    error: '#D7263D',
    border: '#E0E0E0',
    muted: '#BDBDBD',
  },
  fontSizes: {
    ...globalTheme.fontSizes,
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.25rem',
    xl: '2rem',
    '2xl': '2.5rem',
    '3xl': '3rem',
    '4xl': '4rem',
  },
  spacing: {
    ...globalTheme.spacing,
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '32px',
    xl: '64px',
    '2xl': '96px',
    '3xl': '128px',
    '4xl': '192px',
  },
  borderRadius: {
    ...globalTheme.borderRadius,
    none: '0',
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '32px',
    full: '9999px',
  },
  shadows: {
    ...globalTheme.shadows,
    sm: '0 1px 2px rgba(0,0,0,0.05)',
    md: '0 4px 6px rgba(0,0,0,0.1)',
    lg: '0 10px 20px rgba(0,0,0,0.15)',
  },
  transitions: {
    ...globalTheme.transitions,
    fast: '150ms ease-in-out',
    base: '200ms ease-in-out',
    slow: '300ms ease-in-out',
  },
};
