const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, '../src/pages');
const indexFile = path.join(__dirname, '../src/index.tsx');

const dirs = fs.readdirSync(pagesDir, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory())
  .map(dirent => dirent.name);

const header = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by scripts/generate-exports.js on build.
`;

const lines = dirs.map(
  name => `export { default as ${name} } from "@pages/${name}/${name}";`
);

fs.writeFileSync(indexFile, header + lines.join('\n') + '\n');
console.log('index.tsx exports generated!');